x=[0:0.01:10];
y1=lognpdf(x,0,1);
y2=lognpdf(x,0,2);
figure(1);
plot(x,y1,'b');
hold on;
plot(x,y2,'r');
title('lognormal pdf');
xlabel('x');
ylabel('pdf');
legend('lognpdf[x,0,1]','lognpdf[x,0,2]');
figure(2);
plot3(x,y1,y2);
grid;
plot3(y1,y2,x);
grid;
title('lognormal pdf-3-d');
xlabel('lognpdf[x,0,1]');
ylabel('lognpdf[x,0,2]');
zlabel('pdf');